const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Plugins.iframe,
		C3.Plugins.Sprite,
		C3.Plugins.Clipboard,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.TiledBg.Cnds.PickByUID,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerLogin,
		C3.Plugins.Clipboard.Cnds.OnCopySuccess,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.iframe.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{GamePush: 0},
	{GamePushChannels: 0},
	{Браузер: 0},
	{Тач: 0},
	{Якорь: 0},
	{Rub_txt: 0},
	{Fon: 0},
	{Текст2: 0},
	{iframe: 0},
	{Avatar: 0},
	{Back: 0},
	{icons8ключ: 0},
	{Текст3: 0},
	{БуферОбмена: 0},
	{ДвижениеК: 0},
	{Rectangle_: 0},
	{Прикрепить: 0},
	{Copy_TXT: 0}
];

self.InstanceType = {
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	GamePushChannels: class extends self.C3.Plugins.GamePush_Channels.Instance {},
	Браузер: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	Rub_txt: class extends self.ITextInstance {},
	Fon: class extends self.ITiledBackgroundInstance {},
	Текст2: class extends self.ITextInstance {},
	iframe: class extends self.IIframeInstance {},
	Avatar: class extends self.ISpriteInstance {},
	Back: class extends self.ISpriteInstance {},
	icons8ключ: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	БуферОбмена: class extends self.IInstance {},
	Rectangle_: class extends self.ISpriteInstance {},
	Copy_TXT: class extends self.ITextInstance {}
}